version: '3.0'

services:
  pg:
    restart: always
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - "../.env"
    volumes:
      - ./data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


